library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(shiny)
library(dplyr)
library(readr)
library(reshape2)
library(webshot)
library(ggplot2)
library(ggvis)
library(rgdal)
library(mosaic)
library(maptools)
library(maps)
library(stringr)
library(plotly)
library(xts)
library(dygraphs)


# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
